<html>
	<body>
        <div class="ortala">

		    <a name="bitcoin"></a>
            <h3>BİTCOİN</h3>
            <p>Bitcoin, Satoshi Nakamoto adını kullanmış bilinmeyen bir kişi veya grup tarafından 2008'de icat edilmiş bir kriptoparadır. 2009'da bir açık kaynak kodlu yazılım olarak piyasaya sürüldüğünde kullanılmaya başlandı. Herhangi bir merkez bankasına veya tek bir yöneticiye bağlı olmamasıyla da bilinen Bitcoin, aracılara ihtiyaç duyulmadan bitcoin ağında kullanıcıdan kullanıcıya transfer edilebilen, merkezi olmayan bir dijital para birimidir. İşlemler, kriptografi yoluyla network nodes tarafınca doğrulanır ve blockchain adı verilen halka açık bir ana deftere kaydedilir. El Salvador, 6 Haziran 2021 tarihinde senatodan geçen tasarı ile birlikte Bitcoin’i resmi para birimi ilan etmiştir. Bütün devrimsel teknolojilerde olduğu gibi Bitcoin öncülleri ve oluşturucusunun makalesinde atıfta bulunduğu kaynaklar vardır. Wei Dai B-Cash, Nick Szabo BitGold, David Chaum Digicash'ı dijital paraların en ilkel ve devletler tarafından engellenen ilk versiyonlarıdır. Satoshi Nakamoto öncüllerinin yaşadığı bu olumsuz deneyimler kaynaklı olarak kimliğini gizli tutmayı başarmıştır.
Bitcoin ağı 3 Ocak 2009'da hayata geçmiştir. Makalenin yazarı Satoshi Nakamoto'dur. Gerçek ismi, mahlası veya bir ekibe ait unvan olduğu konusunda tartışmalar vardır. Üretilebilecek en fazla Bitcoin sayısı genesis blokta belirtilerek 21 milyonla sınırlandırılmıştır. İlk Bitcoin transferi Satoshi Nakamato'ya geliştirmesi için ona yardım sağlayan kriptograf Hal Finney arasında gerçekleşmiştir. İlk alışveriş 22 Mayıs 2010 tarihinde 10.000 Bitcoin karşılığında pizza alımı ile gerçekleşmiştir.
22 Temmuz 2013 tarihi itibarıyla dolaşımdaki Bitcoinlerin toplam değeri 1.2 milyar dolar seviyesindeyken 26.07.2020 tarihi itibarıyla bu değer 182.967.290 dolar olmuştur. Güncel olarak üretilmiş toplam Bitcoin miktarı 18.443.043 seviyesine ulaşmıştır.</p>

            <a name="ethereum"></a>
            <h3>ETHEREUM</h3>
            <p>Ethereum, ERC-20 kod sistemi sayesinde birçok kripto para biriminin altyapısını oluşturan merkeziyetsiz ve açık kaynak kodlu bir blok zinciridir. Ethereum blok zincirinin kurumsal kripto para birimi ise Ether'dir. Ether, Bitcoin'den sonra en büyük piyasa değerine sahip sanal paradır.
Ethereum, 2013 yılının sonlarında kripto para araştırmacısı ve programcısı Vitalik Buterin tarafından yeni nesil bir blok zinciri olarak önerilmiştir. Ethereum'un geliştirilmesi için gereken maddi kaynak 2014 Temmuz ve Ağustos aylarında kitle fonlaması yöntemiyle internet üzerinden toplanmıştır. Ethereum, 30 Temmuz 2015’te, 11.9 milyon sanal birime karşılık gelecek şekilde “ön madencilik” yöntemiyle hayata geçirilmiştir.
Ether ya da kısa adıyla ETH, Ethereum platformu tarafından üretilen kripto para birimidir. Ether, kripto cüzdanlar arasında takas edilebilir ve madencilik hesaplamalarını karşılamak için kullanılabilir. Ethereum, merkezi olmayan Turing sanal makinesinin [Ethereum Virtual Machine (EVM)] kullanımına olanak verir. Bu sanal makine komutları uluslararası internet ağını kullanarak çalıştırabilir. “Gas”, kendi içinde fiyat hesaplama mekanizmasıdır, spam riskini azaltmak ve kaynakları İnternete yüklemek için kullanılır.
Ocak 2016 itibarıyla, Ethereum protokolü saniyede 25 işlem yapabilir hale gelmiştir. 19 Aralık 2016'da ise Ethereum ilk defa bir gün içinde bir milyon işlemi aşmıştır.
En büyük ikinci kripto para birimi olan Ethereum ağının yerel kripto para birimi olan Ether (ETH), 21 Ekim 2021 tarihinde 4 bin 366 dolara ulaşarak tüm zamanların en yüksek seviyesini görmüştür.</p>

            <a name="tron"></a>
            <h3>TRON</h3>
            <p>TRON, TRX olarak bilinen, sisteme özgü bir kripto para birimine dayalı, Blockchain tabanlı merkezi olmayan bir işletim sistemidir.TRON, 2017 yılında Justin Sun tarafından kuruldu. TRON Vakfı, Çin'in dijital tokenları yasaklamasından kısa bir süre önce bir Initial coin teklifiyle 2017 yılında 70 milyon $ topladı.
TRON'un teknik raporu intihalle suçlandı. Digital Asset Research (DAR) araştırmacıları, Tron kod tabanındaki diğer projelerden kopyalanan birden fazla kod örneği keşfettiler. Ayrıca proje, istemcisi Java-Tron'un EthereumJ'den türetildiğinden bahsetmediği için GNU Kısıtlı Genel Kamu Lisansı v3.0'ı (LGPL) ihlal etmekle suçlandı. Bu suçlamalar, sistemin tasarımının arkasındaki kuruluş olan TRON Vakfı tarafından reddedildi.
2018'de TRON, protokolünü Ethereum'un üstündeki bir ERC-20 belirtecinden bağımsız bir eşler arası ağ ile değiştirdi. Bundan sonra Ethereum'a rakip olacak şekilde pazarlandı. 25 Temmuz 2018'de TRON Vakfı, en büyük eşler arası dosya paylaşım ağı olan BitTorrent'i satın almayı tamamladığını duyurdu. Bu satın alma üzerine, Ağustos 2018 yılında, Bittorrent'in kurucusu Bram Cohen, daha az enerji yoğunluklu bir kripto para birimi olarak yaratılan Bitcoin'e bir alternatif olan Chia'yı kurmak için şirketten ayrıldığını da açıkladı.
Ocak 2019 itibarıyla TRON'un toplam piyasa değeri yaklaşık 1,6 milyar dolardı. Bu pazar performansına rağmen, bazı yazarlar TRON'u kripto para birimlerinin karmaşık ve düzensiz doğasının tipik bir örneği olarak gördü. Şubat 2019'da, Tron Vakfı tarafından satın alındıktan sonra BitTorrent, TRON ağına dayalı olarak kendi token satışını başlattı.
Mayıs 2019'da, siber güvenlik test hizmeti HackerOne, sadece bir bilgisayarın TRON'un tüm blok zincirini durma noktasına getirebileceğini açıkladı. Açıklama, tek bir PC tarafından gönderilen bir istek yığınının, blok zincirinin CPU'sunun gücünü sıkıştırmak, belleği aşırı yüklemek ve dağıtılmış bir hizmet reddi (DDoS) saldırısı gerçekleştirmek için kullanılabileceğini gösterdi.</p>

            <a name="bnb"></a>
            <h3>BNB</h3>
            <p>CEO Changpeng Zhao daha önce 2005 yılında Şangay'da Fusion Systems'ı kurmuştu; şirket, komisyoncular için high-frequency trading sistemleri kurdu. 2013 yılında kripto para cüzdanı ekibinin üçüncü üyesi olarak Blockchain.info'ya katıldı. Ayrıca İtibarî para ve dijital varlıklar arasında spot ticaret platformu olan OKCoin'de bir yıldan kısa bir süre CTO olarak çalıştı,
Şirket Çin'de kuruldu, ancak Eylül 2017'de Çin hükümetinin kripto para birimi ticaretine getirdiği yasaktan önce sunucularını ve genel merkezini Çin'den Japonya'ya taşıdı. Mart 2018 itibarıyla şirket Tayvan'da ofisler kurdu.
İlk kez 26 Haziran - 3 Temmuz 2017 yılında yapılan bir ICO (İlk Para Teklifi) ile birlikte Binance Coin (BNB) piyasaya sürüldü. İlk çıkışta toplam 100.000.000 BNB piyasaya sürülmüştür. Binance Coin (BNB), BEP2 tabanlı bir altyapı modeli ile hizmet veren ve Binance şirketinin geliştirmiş olduğu yeni nesil blockchain modelidir.
Ocak 2018 itibarıyla 1,3 milyar dolarlık piyasa değeri ile en büyük kripto para borsasıydı.
Mart 2018'de Binance, Japonya ve Çin'deki daha katı düzenlemelerin ardından Malta'da bir ofis açma niyetini açıkladı. Nisan 2018'de Binance, Bermuda Hükümeti ile bir Uzlaşı Belgesi (MoU) imzaladı. Aylar sonra, menkul kıymet belirteçleri ticareti için bir platform geliştirmek için Malta Borsası ile benzer bir mutabakat imzalandı. 2019 yılında şirket, Avrupa'da etkisini genişletmek amacıyla ana Binance.com borsasından bağımsız bir kuruluş olan Binance Jersey'i duyurdu. Jersey merkezli değişim, Euro ve İngiliz sterlini dahil olmak üzere fiat-kripto para birimi çiftleri sunuyordu. Binance tarafından yapılan açıklama ile Jersey borsası, Euro ve İngiliz sterlini başta olmak üzere kripto para yatırım işlemlerini 31 Ekim 2020’de kadar bitirdi. 9 Kasım 2020’ye kadar ise kullanıcılar borsa içerisinde alım-satım ve çekimlerini gerçekleştirebildiler. Borsanın tamamen kapanması ise 30 Kasım 2020'de oldu.
Ağustos 2018'de Binance, diğer üç büyük borsa ile birlikte stable coin projesi için 32 milyon dolar topladı. stable coin fikrinin amacı Bitcoinin ve diğer popüler dijital varlıkların dalgalı fiyatlarına karşın stabil bir kripto para birimi sağlamaktır.
Ocak 2019'da Binance, Visa ve Mastercard dahil olmak üzere banka ve kredi kartlarıyla kripto para satın alımlarını mümkün kılmak için İsrail merkezli ödeme işlemcisi Simplex ile ortaklık kurduğunu duyurdu. Satın alımlar Simplex'in yerel banka politikalarına tabidir ve Bitcoin, Ethereum, Litecoin ve Ripple'nin XRP'si ile sınırlıdır.</p>
        </div>
    </body>
</html>